### PR TITLE
added https for rubygem and new rubies

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by antifuchs** [comment]
Thanks for submitting this! Looking at CI results, it seems like the JSON gem needs a bump; do you mind updating it in the bundle as part of this PR? (:

**Comment by ferdinandrosario** [comment]
Sure I did & and thanks for the prompt reply :smiley:

**Comment by ferdinandrosario** [comment]
Build passed.

**Comment by antifuchs** [comment]
Brilliant! Thanks again (:

**Comment by ferdinandrosario** [comment]
:+1:

**Pull request merged**
